[build]
  command = "npm install"
  functions = "functions"
  publish = "dist"

[functions]
  external_node_modules = ["express", "pg", "pg-hstore"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api"
